# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01cb46b0259cac075b9326cb777d7cd518d302f7c352e4a2b18f89f5b5bfd644839904c02db12456b9f4f99d134f0de2bedc73e04d33a42197db5350fc76ec71

test:
  secret_key_base: a763de33fec64b4e0882ca4166edb126962506b36ed179d1b368cf51678a3996d33fc606dd3b770cc4f9fb2e8bc43ce6ea17e519c2f22ee4c895803c6b5112fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
